### ISSUE TITLE
gcc compiler issue

### ISSUE THREAD

**Issue by haroon-oxts** [OxfordTechnicalSolutions/NCOMdecoder#9]
I think it’s only compiler options. I’ve just tested it on a debian machine as I had one to hand with git and GCC – I didn’t have a MinGW installation on my current laptop. Full commands and output below:

kim@kim04:~$ git clone https://github.com/OxfordTechnicalSolutions/NCOMdecoder

Cloning into 'NCOMdecoder'...

remote: Counting objects: 142, done.

remote: Compressing objects: 100% (49/49), done.

remote: Total 142 (delta 40), reused 75 (delta 29), pack-reused 50

Receiving objects: 100% (142/142), 6.84 MiB | 5.13 MiB/s, done.

Resolving deltas: 100% (51/51), done.

kim@kim04:~$ cd NCOMdecoder

kim@kim04:~/NCOMdecoder$ ls

example measurements.csv nav README.md

kim@kim04:~/NCOMdecoder$ cd example

kim@kim04:~/NCOMdecoder/example$ ls

171019_031603.ncom Makefile NcomToCsv.c

kim@kim04:~/NCOMdecoder/example$ make

gcc -I../nav -c -o ../nav/NComRxC.o ../nav/NComRxC.c

gcc -I../nav -c -o NcomToCsv.o NcomToCsv.c

gcc -o NComToCsv ../nav/NComRxC.o NcomToCsv.o -I../nav

../nav/NComRxC.o: In function `SpeedSlipCompute':

NComRxC.c:(.text+0xd461): undefined reference to `sqrt'

NComRxC.c:(.text+0xd496): undefined reference to `sqrt'

And then it continues to die – lots of errors with missing maths functions

#####################################################################

If you edit the makefile to specify it should include the maths libraries by default – add –lm:

CFLAGS=-I$(IDIR) –lm

Then it compiles silently and you get an executable which works.

kim@kim04:~/NCOMdecoder/example$ make

gcc -o NComToCsv ../nav/NComRxC.o NcomToCsv.o -I../nav –lm

kim@kim04:~/NCOMdecoder/example$ ls

171019_031603.ncom Makefile NComToCsv NcomToCsv.c NcomToCsv.o

kim@kim04:~/NCOMdecoder/example$ ./NComToCsv 171019_031603.ncom out.csv

NcomToCsv: Converts NCom file data to text. (ID: 161005)

MinGW may include that option by default, so it may well work as you say, but I suspect it doesn’t hurt to add it, and it makes it work on a plain gcc system.

**Comment by HMellor** [comment]
Fixed in #10
